#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : R-sessioninfo
Version  : 1.2.3
Release  : 45
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/sessioninfo_1.2.3.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/sessioninfo_1.2.3.tar.gz
Summary  : R Session Information
Group    : Development/Tools
License  : GPL-2.0
Requires: R-cli
BuildRequires : R-cli
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# sessioninfo
> R Session Information
<!-- badges: start -->
[![Lifecycle: stable](https://lifecycle.r-lib.org/articles/figures/lifecycle-stable.svg)](https://lifecycle.r-lib.org/articles/stages.html)
[![R-CMD-check](https://github.com/r-lib/sessioninfo/actions/workflows/R-CMD-check.yaml/badge.svg)](https://github.com/r-lib/sessioninfo/actions/workflows/R-CMD-check.yaml)
[![](https://www.r-pkg.org/badges/version/sessioninfo)](https://www.r-pkg.org/pkg/sessioninfo)
[![CRAN RStudio mirror downloads](https://cranlogs.r-pkg.org/badges/sessioninfo)](https://www.r-pkg.org/pkg/sessioninfo)
[![Codecov test coverage](https://codecov.io/gh/r-lib/sessioninfo/branch/main/graph/badge.svg)](https://app.codecov.io/gh/r-lib/sessioninfo?branch=main)
<!-- badges: end -->

%prep
%setup -q -n sessioninfo
pushd ..
cp -a sessioninfo buildavx2
popd
pushd ..
cp -a sessioninfo buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1738795432

%install
export SOURCE_DATE_EPOCH=1738795432
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/sessioninfo/DESCRIPTION
/usr/lib64/R/library/sessioninfo/INDEX
/usr/lib64/R/library/sessioninfo/Meta/Rd.rds
/usr/lib64/R/library/sessioninfo/Meta/features.rds
/usr/lib64/R/library/sessioninfo/Meta/hsearch.rds
/usr/lib64/R/library/sessioninfo/Meta/links.rds
/usr/lib64/R/library/sessioninfo/Meta/nsInfo.rds
/usr/lib64/R/library/sessioninfo/Meta/package.rds
/usr/lib64/R/library/sessioninfo/NAMESPACE
/usr/lib64/R/library/sessioninfo/NEWS.md
/usr/lib64/R/library/sessioninfo/R/sessioninfo
/usr/lib64/R/library/sessioninfo/R/sessioninfo.rdb
/usr/lib64/R/library/sessioninfo/R/sessioninfo.rdx
/usr/lib64/R/library/sessioninfo/R/sysdata.rdb
/usr/lib64/R/library/sessioninfo/R/sysdata.rdx
/usr/lib64/R/library/sessioninfo/help/AnIndex
/usr/lib64/R/library/sessioninfo/help/aliases.rds
/usr/lib64/R/library/sessioninfo/help/figures/session-info2.svg
/usr/lib64/R/library/sessioninfo/help/paths.rds
/usr/lib64/R/library/sessioninfo/help/sessioninfo.rdb
/usr/lib64/R/library/sessioninfo/help/sessioninfo.rdx
/usr/lib64/R/library/sessioninfo/html/00Index.html
/usr/lib64/R/library/sessioninfo/html/R.css
/usr/lib64/R/library/sessioninfo/tests/testthat.R
/usr/lib64/R/library/sessioninfo/tests/testthat/_snaps/diff.md
/usr/lib64/R/library/sessioninfo/tests/testthat/_snaps/platform-info.md
/usr/lib64/R/library/sessioninfo/tests/testthat/fixtures/MD5
/usr/lib64/R/library/sessioninfo/tests/testthat/fixtures/biobase.rda
/usr/lib64/R/library/sessioninfo/tests/testthat/fixtures/descs.rda
/usr/lib64/R/library/sessioninfo/tests/testthat/fixtures/devtools-deps.rda
/usr/lib64/R/library/sessioninfo/tests/testthat/fixtures/devtools-info-unix.rda
/usr/lib64/R/library/sessioninfo/tests/testthat/fixtures/devtools-info-windows.rda
/usr/lib64/R/library/sessioninfo/tests/testthat/fixtures/devtools.rda
/usr/lib64/R/library/sessioninfo/tests/testthat/fixtures/fsdfgwetdhsdfhq4yqh_0.0.0.9000.tar.gz
/usr/lib64/R/library/sessioninfo/tests/testthat/fixtures/gh.html.gz
/usr/lib64/R/library/sessioninfo/tests/testthat/fixtures/installed.rda
/usr/lib64/R/library/sessioninfo/tests/testthat/fixtures/lines1.txt
/usr/lib64/R/library/sessioninfo/tests/testthat/fixtures/lines2.txt
/usr/lib64/R/library/sessioninfo/tests/testthat/fixtures/lines3.txt
/usr/lib64/R/library/sessioninfo/tests/testthat/fixtures/lines4.txt
/usr/lib64/R/library/sessioninfo/tests/testthat/fixtures/memoise.rda
/usr/lib64/R/library/sessioninfo/tests/testthat/fixtures/no-remote-repo.rda
/usr/lib64/R/library/sessioninfo/tests/testthat/fixtures/no-sha.rda
/usr/lib64/R/library/sessioninfo/tests/testthat/test-dependent-packages.R
/usr/lib64/R/library/sessioninfo/tests/testthat/test-diff.R
/usr/lib64/R/library/sessioninfo/tests/testthat/test-loaded-packages.R
/usr/lib64/R/library/sessioninfo/tests/testthat/test-os-name.R
/usr/lib64/R/library/sessioninfo/tests/testthat/test-package-info.R
/usr/lib64/R/library/sessioninfo/tests/testthat/test-platform-info.R
/usr/lib64/R/library/sessioninfo/tests/testthat/test-printing.R
/usr/lib64/R/library/sessioninfo/tests/testthat/test-session-info.R
/usr/lib64/R/library/sessioninfo/tests/testthat/test-utils.R
/usr/lib64/R/library/sessioninfo/tests/testthat/test-warnings.R
